version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build-and-test:
    executor: python/default
    # docker:
    #   - image: circleci/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          # update once moved to root
          command: ./project/manage.py test --pattern="test_*.py"
          name: Test
      - slack/status:
          webhook: "${SLACK_WEBHOOK}"

workflows:
  main:
    jobs:
      - build-and-test
