version: "3"

services:
  web:
    build: .
    # context: .
    # dockerfile: docker/app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  # db-init:
  #   build:
  #     context: .
  #     dockerfile: docker/db-init/Dockerfile
  #   depends_on:
  #     - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=toggleme
      - POSTGRES_PASSWORD=ss

# persist the data beyond the life of the container
volumes:
  postgres_data:
