version: "3"

services:
    web:
        build:
            context: .
            dockerfile: docker/Dockerfile
        command: docker/docker-entrypoint.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        # image: postgres:12
        # image: python/default
        # restart: always
        #./docker/db
        build:
            context: ./sql
            dockerfile: Dockerfile
        # docker/db/Dockerfile
        # container_name: project_db
        # entrypoint: ./
        volumes:
            # - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
            # - ./sql/create.sql:/docker-entrypoint-initdb.d/2-create.sql
            # - ./sql/test_data.sql:/docker-entrypoint-initdb.d/3-test_data.sql
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=project
            - POSTGRES_USER=toggleme
            - POSTGRES_PASSWORD=ss
# persist the data beyond the life of the container
volumes:
    postgres_data:
